### ISSUE TITLE
Removed fluxible store

### ISSUE THREAD

**Issue by jamesjjk** [zoover/react-i18nify#1]
@gerbenmeyer Hi, like your component but you have removed the fluxible store entirely? Will it be coming back.

**Comment by gerbenmeyer** [comment]
@jamesjjk It seemed that the store was not needed, and the package could be made more generic. So in our case, we just replaced `actionContext.dispatch('LOAD_TRANSLATIONS', {...});` with `I18n.loadTranslations({...});` and similarly for setting the locale. But if it's more convenient to use the store, I can undeprecate react-i18n-fluxible, and make it an extension of this package.

**Comment by gerbenmeyer** [comment]
Ok, so I've one just that, so now you can use the store again :)
