### ISSUE TITLE
Warning: forceUpdate(...): Can only update a mounting component

### ISSUE THREAD

**Issue by jamesjjk** [zoover/react-i18nify#11]
Hi After updating from react-fluxible-i18n from 1.1.0 to 1.6.0 the following error message is thrown. Notably this happens during the render lifecycle server side on isomorphic applications:

```
Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op. Please check the code for the Translate component.
```

**Comment by tikider** [comment]
Thank you for reporting that issue. It is now fixed in the latest version.
