### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by ido-ran** [zoover/react-i18nify#14]
I'm looking for way to handle line break in translation.
I do not want to split lines to different i18n keys because different languages might have different line breaks.
How can I split lines in translation?

**Comment by gerbenmeyer** [comment]
Currently this is not supported, but I think it would be nicer (and more generic) to support HTML, as suggested here: https://github.com/zoover/react-i18nify/issues/15

In that case, you could just use `<br/>`.

**Comment by ido-ran** [comment]
I'm using react-i18nify via react-redux-i18n@0.1.0 and when I put `<br />` inside a translation it show it as plain text and not taking it as html markup.

**Comment by mhlavacka** [comment]
I def agree. We have one element where we need to use HTML inside of Translate component. Unfortunately, this prevents us from using this great package in production right now.
