### ISSUE TITLE
React-warning-dont-call-proptypes

### ISSUE THREAD

**Issue by mieryn** [zoover/react-i18nify#4]
Hi,

Nice components, but today I got warnings that I believe come from react-i18nify (I'm using react-redux-i18n).

Warning: You are manually calling a React.PropTypes validation function for the `value` prop on `Translate`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Warning: You are manually calling a React.PropTypes validation function for the `value` prop on `Localize`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Warning: You are manually calling a React.PropTypes validation function for the `options` prop on `Localize`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Warning: You are manually calling a React.PropTypes validation function for the `dateFormat` prop on `Localize`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by gerbenmeyer** [comment]
Actually, I don't see where we are calling a React.PropTypes validation function. Could it be that this is happening in your code?

**Comment by mieryn** [comment]
I also got these errors with your example code (slightly modified in render):

`var React = require('react');
import ReactDOM from 'react-dom'

var I18n = require('react-i18nify').I18n;
var Translate = require('react-i18nify').Translate;
var Localize = require('react-i18nify').Localize;

I18n.loadTranslations({
  en: {
    application: {
      title: 'Awesome app with i18n!',
      hello: 'Hello, %{name}!'
    },
    date: {
      long: 'MMMM Do, YYYY'
    }
  },
  nl: {
    application: {
      title: 'Toffe app met i18n!',
      hello: 'Hallo, %{name}!'
    },
    date: {
      long: 'D MMMM YYYY'
    }
  }
});

I18n.setLocale('nl');

console.log(I18n.t('application.title'));
console.log(I18n.t('application.hello', {name: 'Aad'}));
console.log(I18n.t('application.weird_key'));
console.log(I18n.l(1385856000000, { dateFormat: 'date.long' }));
console.log(I18n.l(Math.PI, { maximumFractionDigits: 2 }));

function AwesomeComponent() {
  return (
    <div>
      <Translate value="application.title"/><br/>
      <Translate value="application.hello" name="Aad"/><br/>
      <Localize value="2015-09-03" dateFormat="date.long"/><br/>
      <Localize value={10/3} options={{style: 'currency', currency: 'EUR', minimumFractionDigits: 2, maximumFractionDigits: 2}}/><br/>
    </div>
  );
}

const rootEl = document.getElementById('root')

function render() {
  ReactDOM.render(
    <AwesomeComponent/>,
    rootEl  
  )
}

render()
`

**Comment by mieryn** [comment]
I also got these errors with your example code (slightly modified about rendering):

```javascript
var React = require('react');
import ReactDOM from 'react-dom'

var I18n = require('react-i18nify').I18n;
var Translate = require('react-i18nify').Translate;
var Localize = require('react-i18nify').Localize;

I18n.loadTranslations({
  en: {
    application: {
      title: 'Awesome app with i18n!',
      hello: 'Hello, %{name}!'
    },
    date: {
      long: 'MMMM Do, YYYY'
    }
  },
  nl: {
    application: {
      title: 'Toffe app met i18n!',
      hello: 'Hallo, %{name}!'
    },
    date: {
      long: 'D MMMM YYYY'
    }
  }
});

I18n.setLocale('nl');

console.log(I18n.t('application.title'));
console.log(I18n.t('application.hello', {name: 'Aad'}));
console.log(I18n.t('application.weird_key'));
console.log(I18n.l(1385856000000, { dateFormat: 'date.long' }));
console.log(I18n.l(Math.PI, { maximumFractionDigits: 2 }));

function AwesomeComponent() {
  return (
    <div>
      <Translate value="application.title"/><br/>
      <Translate value="application.hello" name="Aad"/><br/>
      <Localize value="2015-09-03" dateFormat="date.long"/><br/>
      <Localize value={10/3} options={{style: 'currency', currency: 'EUR', minimumFractionDigits: 2, maximumFractionDigits: 2}}/><br/>
    </div>
  );
}

const rootEl = document.getElementById('root')

function render() {
  ReactDOM.render(
    <AwesomeComponent/>,
    rootEl  
  )
}

render()

```

**Comment by gerbenmeyer** [comment]
We don't get any warnings when running this code, how are you running this code?

**Comment by mieryn** [comment]
I replaced index.js of this example ( https://github.com/reactjs/redux/tree/master/examples/counter ) with the code above, ran `npm install`, `npm i react-i18nify --save` and `npm start`.

**Comment by gerbenmeyer** [comment]
Doing that, I also got the same warnings. But the react version used in that example is rather outdated. So I updated the package.json in the following way, and all warnings were gone. 

```
 react                    ^0.14.7  →  ^15.3.1 
 react-dom                ^0.14.7  →  ^15.3.1 
 cross-env                 ^1.0.7  →   ^2.0.0 
 mocha                     ^2.2.5  →   ^3.0.2 
 node-libs-browser         ^0.5.2  →   ^1.0.0 
 react-addons-test-utils  ^0.14.7  →  ^15.3.1 
```

**Comment by mieryn** [comment]
Okay, thanks!
